//  This file is generated by the UI. There's no point in editing.
#include "../DeviceSource/PokemonSwShPrograms/ShinyHunt-Regi.h"
const uint16_t WAIT_TIME = 1875;
const uint32_t TOUCH_DATE_INTERVAL = 1800000;
